"""Per-span network inventory: heterogeneous spans and amplifiers.

A :class:`NetworkInventory` lists, for every link of a topology, the spans that
make it up: fibre length and loss coefficient, lumped connector losses and the
amplifier at the end of each span (equipment type, noise figure and gain-ripple
transform). Field names follow the GNPy network description where possible
(``con_in``/``con_out``, ``type_variety``) [Curri_2022_GNPyModelPhysical].

The inventory is plain JSON (``format: "ong-network-inventory/v1"``), so it can
be versioned, diffed and generated by external tools. Two inventories of the
same network, e.g. the operator's nominal records and the "true" deployed
network, are applied to the same topology with :func:`apply_inventory` to obtain
two :class:`TopologyModel` objects that share routes and differ only in their
physical layer.

Resolution rules when building :class:`Span` objects:

* The amplifier gain equals the span's total loss (fibre + lumped losses).
* An explicit ``noise_figure_db`` wins; otherwise the NF is computed from the
  equipment type's NF model at that gain (see ``equipment.AmplifierType``).
* The gain ripple is the equipment type's measured profile, scaled and shifted
  per amplifier (``gain_ripple_scale``, ``gain_ripple_shift_hz``) as done in
  [Mahajan_2020_ModelingEDFAGain]; a scale of 0 means flat gain.

References are listed at the end of the file.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
import json
from pathlib import Path
from typing import Any, Mapping

from .equipment import EquipmentLibrary
from .topology import Link, Span, TopologyModel, _canonical_pair

__all__ = [
    "AmplifierRecord",
    "INVENTORY_FORMAT",
    "LinkRecord",
    "NetworkInventory",
    "SpanRecord",
    "apply_inventory",
]

INVENTORY_FORMAT = "ong-network-inventory/v1"


@dataclass(frozen=True, slots=True)
class AmplifierRecord:
    """The amplifier at the end of a span."""

    type_variety: str | None = None
    noise_figure_db: float | None = None
    gain_ripple_scale: float = 1.0
    gain_ripple_shift_hz: float = 0.0

    def to_mapping(self) -> dict[str, Any]:
        return {
            "type_variety": self.type_variety,
            "noise_figure_db": self.noise_figure_db,
            "gain_ripple_scale": self.gain_ripple_scale,
            "gain_ripple_shift_hz": self.gain_ripple_shift_hz,
        }

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "AmplifierRecord":
        nf = payload.get("noise_figure_db")
        return cls(
            type_variety=payload.get("type_variety"),
            noise_figure_db=None if nf is None else float(nf),
            gain_ripple_scale=float(payload.get("gain_ripple_scale", 1.0)),
            gain_ripple_shift_hz=float(payload.get("gain_ripple_shift_hz", 0.0)),
        )


@dataclass(frozen=True, slots=True)
class SpanRecord:
    """One span: fibre, lumped losses and its amplifier."""

    length_km: float
    loss_coef_db_per_km: float
    con_in_db: float = 0.0
    con_out_db: float = 0.0
    amplifier: AmplifierRecord = field(default_factory=AmplifierRecord)

    def __post_init__(self) -> None:
        if self.length_km <= 0 or self.loss_coef_db_per_km <= 0:
            raise ValueError("span length and loss coefficient must be positive")
        if self.con_in_db < 0 or self.con_out_db < 0:
            raise ValueError("connector losses must be non-negative")

    @property
    def total_loss_db(self) -> float:
        return self.length_km * self.loss_coef_db_per_km + self.con_in_db + self.con_out_db

    def to_mapping(self) -> dict[str, Any]:
        return {
            "length_km": self.length_km,
            "loss_coef_db_per_km": self.loss_coef_db_per_km,
            "con_in_db": self.con_in_db,
            "con_out_db": self.con_out_db,
            "amplifier": self.amplifier.to_mapping(),
        }

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "SpanRecord":
        return cls(
            length_km=float(payload["length_km"]),
            loss_coef_db_per_km=float(payload["loss_coef_db_per_km"]),
            con_in_db=float(payload.get("con_in_db", 0.0)),
            con_out_db=float(payload.get("con_out_db", 0.0)),
            amplifier=AmplifierRecord.from_mapping(payload.get("amplifier", {})),
        )


@dataclass(frozen=True, slots=True)
class LinkRecord:
    """The spans of the link between two nodes (order: source to target)."""

    source: str
    target: str
    spans: tuple[SpanRecord, ...]

    def __post_init__(self) -> None:
        if not self.spans:
            raise ValueError(f"link {self.source}-{self.target} needs at least one span")

    def to_mapping(self) -> dict[str, Any]:
        return {
            "source": self.source,
            "target": self.target,
            "spans": [span.to_mapping() for span in self.spans],
        }

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "LinkRecord":
        return cls(
            source=str(payload["source"]),
            target=str(payload["target"]),
            spans=tuple(SpanRecord.from_mapping(span) for span in payload["spans"]),
        )


@dataclass(frozen=True, slots=True)
class NetworkInventory:
    """Physical-layer inventory of all links of a topology."""

    topology_id: str
    links: tuple[LinkRecord, ...]
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def to_mapping(self) -> dict[str, Any]:
        return {
            "format": INVENTORY_FORMAT,
            "topology_id": self.topology_id,
            "metadata": dict(self.metadata),
            "links": [link.to_mapping() for link in self.links],
        }

    def to_json(self, file_path: str | Path) -> Path:
        """Write the inventory as indented JSON."""
        path = Path(file_path)
        path.write_text(json.dumps(self.to_mapping(), indent=1) + "\n", encoding="utf-8")
        return path

    @classmethod
    def from_mapping(cls, payload: Mapping[str, Any]) -> "NetworkInventory":
        if payload.get("format") != INVENTORY_FORMAT:
            raise ValueError(f"unsupported inventory format {payload.get('format')!r}")
        return cls(
            topology_id=str(payload["topology_id"]),
            links=tuple(LinkRecord.from_mapping(link) for link in payload["links"]),
            metadata=dict(payload.get("metadata", {})),
        )

    @classmethod
    def from_json(cls, file_path: str | Path) -> "NetworkInventory":
        return cls.from_mapping(json.loads(Path(file_path).read_text(encoding="utf-8")))

    @classmethod
    def from_topology(
        cls,
        topology: TopologyModel,
        *,
        amplifier_type: str | None = None,
        noise_figure_db: float | None = None,
        con_in_db: float = 0.0,
        con_out_db: float = 0.0,
        gain_ripple_scale: float = 0.0,
    ) -> "NetworkInventory":
        """Nominal inventory mirroring the spans already present in ``topology``.

        Span lengths and loss coefficients are copied; every amplifier gets the
        same type, NF (``None`` = computed from the equipment type, or the
        topology's span NF when no type is given) and ripple scale.
        """
        links = []
        for link in topology.links:
            spans = tuple(
                SpanRecord(
                    length_km=span.length_km,
                    loss_coef_db_per_km=span.attenuation_db_per_km,
                    con_in_db=con_in_db,
                    con_out_db=con_out_db,
                    amplifier=AmplifierRecord(
                        type_variety=amplifier_type,
                        noise_figure_db=(
                            noise_figure_db
                            if noise_figure_db is not None or amplifier_type is not None
                            else span.noise_figure_db
                        ),
                        gain_ripple_scale=gain_ripple_scale,
                    ),
                )
                for span in link.spans
            )
            links.append(LinkRecord(source=link.source_name, target=link.target_name, spans=spans))
        return cls(topology_id=topology.topology_id, links=tuple(links))


def _resolve_span(record: SpanRecord, equipment: EquipmentLibrary | None) -> Span:
    amplifier = record.amplifier
    amp_type = None
    if amplifier.type_variety is not None:
        if equipment is None:
            raise ValueError(f"amplifier type '{amplifier.type_variety}' needs an equipment library")
        amp_type = equipment.amplifier(amplifier.type_variety)
    if amplifier.noise_figure_db is not None:
        noise_figure_db = amplifier.noise_figure_db
    elif amp_type is not None:
        noise_figure_db = amp_type.noise_figure_db(record.total_loss_db)
    else:
        raise ValueError("span amplifier needs noise_figure_db or an equipment type_variety")
    gain_ripple = None
    if amp_type is not None and amp_type.gain_ripple is not None and amplifier.gain_ripple_scale != 0.0:
        gain_ripple = amp_type.gain_ripple.transformed(
            scale=amplifier.gain_ripple_scale, shift_hz=amplifier.gain_ripple_shift_hz
        )
    return Span(
        length_km=record.length_km,
        attenuation_db_per_km=record.loss_coef_db_per_km,
        noise_figure_db=noise_figure_db,
        input_loss_db=record.con_in_db,
        output_loss_db=record.con_out_db,
        amplifier_type=amplifier.type_variety,
        gain_ripple=gain_ripple,
    )


def apply_inventory(
    topology: TopologyModel,
    inventory: NetworkInventory,
    equipment: EquipmentLibrary | None = None,
) -> TopologyModel:
    """Return a copy of ``topology`` whose link spans come from ``inventory``.

    Routes, node and link indices are unchanged, so paths computed on the plain
    topology remain valid. Every link must be present exactly once.

    Raises:
        ValueError: On missing, duplicated or unknown links.
    """
    spans_by_link: dict[int, tuple[Span, ...]] = {}
    for record in inventory.links:
        key = _canonical_pair(record.source, record.target, topology.node_index_by_name)
        if key not in topology.link_id_by_endpoints:
            raise ValueError(f"inventory link {record.source}-{record.target} not in topology")
        link_id = topology.link_id_by_endpoints[key]
        if link_id in spans_by_link:
            raise ValueError(f"inventory lists link {record.source}-{record.target} twice")
        spans_by_link[link_id] = tuple(_resolve_span(span, equipment) for span in record.spans)
    missing = [link.id for link in topology.links if link.id not in spans_by_link]
    if missing:
        raise ValueError(f"inventory misses link ids {missing}")
    links: list[Link] = [replace(link, spans=spans_by_link[link.id]) for link in topology.links]
    return replace(topology, links=tuple(links))


# References
# [Curri_2022_GNPyModelPhysical] V. Curri, "GNPy Model of the Physical Layer for Open
#     and Disaggregated Optical Networking [Invited]," Journal of Optical Communications
#     and Networking, vol. 14, no. 6, pp. C92-C104, Jun. 2022, doi: 10.1364/JOCN.452868.
# [Mahajan_2020_ModelingEDFAGain] A. Mahajan, K. Christodoulopoulos, R. Martinez,
#     S. Spadaro, and R. Munoz, "Modeling EDFA Gain Ripple and Filter Penalties With
#     Machine Learning for Accurate QoT Estimation," Journal of Lightwave Technology,
#     vol. 38, no. 9, pp. 2616-2629, May 2020, doi: 10.1109/JLT.2020.2975081.
